sonar.projectKey=CryptoManiac441_stellar_forensics
sonar.projectName=stellar_forensics
sonar.sources=src
sonar.tests=test
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**,diagnostics/**,diagnostics-cells/**,diagnostics-summary/**
